# List all clusters under pos_sel that have a BLAST homolog
#
# Example:
#
#   env HASH="by_gene=1,species=Mh,source1=CDS" ../../../scripts/sparql.sh blast2.rq
#
# Optionally provide a source2 or blast (refseq|species) to match against
<%
   h=ENV['HASH'].split(',').map{ |s| s.split('=') }.to_h
   # inputs
   species     = h['species']
   source1     = h['source1']
   source2     = h['source2']
   blast       = h['blast']
   # options
   by_cluster  = h['by_cluster']       # clusters only
   by_gene     = h['by_gene']       # list all genes
%>

<%= File.read(File.dirname(__FILE__)+'/preamble.rq')  %>

<% if not by_gene %>
  <% if by_cluster %>
    SELECT DISTINCT ?cluster WHERE
  <% else %>
    SELECT DISTINCT ?cluster ?hspecies WHERE 
  <% end %>
<% else %>
  SELECT ?cluster ?hspecies ?hspecies_full ?gdescr WHERE 
<% end %>
{

# :Mi_CDS_cluster00100_NP_001022867 gwp:cluster :Mi_CDS_cluster00100 .
# :Mi_CDS_cluster00100_NP_001022867 a :blast_match .
# :Mi_CDS_cluster00100_NP_001022867 rdf:label "Mi_CDS_cluster00100_NP_001022867" .
# :Mi_CDS_cluster00100_NP_001022867 :homolog_species "Ce" .
# :Mi_CDS_cluster00100_NP_001022867 :homolog_species_full "Caenorhabditis elegans" .
# :Mi_CDS_cluster00100_NP_001022867 :homolog_gene "NP_001022867" .
# :Mi_CDS_cluster00100_NP_001022867 :descr "Protein MVK-1, isoform b  > Protein MVK-1, isoform b" .
# :Mi_CDS_cluster00100_NP_001022867 :e_value 9.42776e-164 .

  ?hgene
    gwp:cluster ?cluster ;    # <--- note the NS may change
    <% if blast %>
    a blast:<%= blast %>_match ;
    <% end %>
    <% if source2 %>blast:homolog_source "<%= source2 %>" ; <% end %>
    blast:homolog_species_full ?hspecies_full ;
    blast:homolog_species ?hspecies .
  ?cluster  # The cluster we are matching
    paml:species "<%= species %>" ;
    paml:source "<%= source1 %>" ;
    paml:is_pos_sel true .
  MINUS  { ?hgene blast:homolog_species "<%= species %>" } .
  FILTER ( !CONTAINS(?hspecies_full,"Nema_EST")) .
  OPTIONAL  { ?hgene blast:descr ?gdescr } .
}
