# Count all clusters under positive selection
#
# Run with, for example:
#
# ~/opt/bin/sparql-query http://localhost:8000/sparql/ -p < sparql/extra/gwp/count_pos_sel.rq
#
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix dc: <http://purl.org/dc/elements/1.1/>
prefix hgnc: <http://identifiers.org/hgnc.symbol/>
prefix doi: <http://dx.doi.org/>
prefix : <http://biobeat.org/rdf/ns#> 

SELECT ?species ?source (COUNT(?id) AS ?num) WHERE 
# SELECT ?name ?source ?sites WHERE 
{ 
  ?id :species ?species .
  ?id :source ?source .
  ?id :is_pos_sel ?is_pos_sel
}
GROUP by ?species ?source
ORDER by ?species ?source
