# Count all clusters under positive selection that match against
# same species
#
# ~/opt/bin/sparql-query http://localhost:8000/sparql/ -p < sparql/extra/gwp/count_pos_sel_with_species_matches.rq
#
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix dc: <http://purl.org/dc/elements/1.1/>
prefix hgnc: <http://identifiers.org/hgnc.symbol/>
prefix doi: <http://dx.doi.org/>
prefix : <http://biobeat.org/rdf/ns#> 


# SELECT ?species ?source (COUNT(?name) AS ?num) WHERE 
SELECT ?species ?source ?cluster (COUNT(?seq) AS ?num) WHERE 
{
  # Find all families and species under pos sel
  ?fam :is_pos_sel true .
  ?fam :species ?species .
  ?fam :cluster ?cluster .
  ?fam :source ?source .

  # Match Blast results in same cluster
  ?seq a :blast_match .
  ?seq :cluster ?cluster .
  ?seq :homolog_species ?hspecies .
  # ?seq :descr   ?descr .
  # ?id rdf:label ?name .
  # FILTER (?species =  ?species2) .
  FILTER (?species != ?hspecies) .
}
GROUP by ?cluster
# ORDER by ?species ?source 
