# Count all clusters under positive selection
#
# Run with, for example:
#
# ~/opt/bin/sparql-query http://localhost:8000/sparql/ -p < sparql/extra/gwp/count_pos_sel.rq
#
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix dc: <http://purl.org/dc/elements/1.1/>
prefix hgnc: <http://identifiers.org/hgnc.symbol/>
prefix doi: <http://dx.doi.org/>
prefix : <http://biobeat.org/rdf/ns#> 

<%
   # inputs
   species     = ENV['species']
   source      = ENV['source']
   count       = ENV['count']
%>

<% if count %>
SELECT ?species ?source (COUNT(?name) AS ?num) WHERE 
<% else %>
SELECT ?species ?source ?id WHERE 
<% end %>
# SELECT ?name ?source ?sites WHERE 
{ 
  ?id :is_pos_sel true .
  ?id rdf:label ?name .
  ?id :sites ?sites .
  <% if species %>
  ?id :species "<%= species %>" .
  <% end %>
  ?id :species ?species .
  <% if source %>
  ?id :source "<%= source %>" .
  <% end %>
  ?id :source ?source .
}
<% if count %>
GROUP by ?species ?source
ORDER by ?species ?source
<% end %>
