# Count all clusters tested for positive selection
#
# Run with, for example:
#
#   ~/opt/bin/sparql-query http://localhost:8000/sparql/ -p < count.rq
#
# or
#
#   ../../../scripts/sparql.sh count.rq
#
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix dc: <http://purl.org/dc/elements/1.1/>
prefix hgnc: <http://identifiers.org/hgnc.symbol/>
prefix doi: <http://dx.doi.org/>
prefix : <http://biobeat.org/rdf/paml#>  

<%
   h=ENV['HASH'].split(',').map{ |s| s.split('=') }.to_h
   is_pos_sel       = h['is_pos_sel']
   count = h['count'] != 'false'
%>

<% if count %>
SELECT ?species ?source (COUNT(?id) AS ?num) WHERE 
<% else %>
SELECT ?id ?species ?source WHERE 
<% end %>
{ 
  ?id :species ?species ;
      :source ?source ;
      :model "M78" .
  <% if is_pos_sel %>
  ?id :is_pos_sel true .
  <% end %>
}
<% if count %>
GROUP by ?species ?source
# ORDER by ?species ?source
<% end %>