# List all clusters that have within dataset matches
#
# ./scripts/sparql.sh script.rq
# 
# List all Mi CDS that have Mi DNA matches
#
#   env HASH="species1=Mi,source1=CDS,species2=Mi,source2=DNA" erb sparql/extra/gwp/match_clusters.rq |~/opt/bin/sparql-query "http://localhost:8000/sparql/?soft-limit=-1" -p
#
# List all Mi CDS with matching DNA matches
# 
#   env HASH="paired=1,species1=Mi,source1=CDS,species2=Mi,source2=DNA" erb sparql/extra/gwp/match_clusters.rq |~/opt/bin/sparql-query "http://localhost:8000/sparql/?soft-limit=-1" -p |sort
#
# List all DNA sequences matching Mi CDS
#
#   env HASH="by_gene=1,species1=Mi,source1=CDS,species2=Mi,source2=DNA" erb sparql/extra/gwp/match_clusters.rq |~/opt/bin/sparql-query "http://localhost:8000/sparql/?soft-limit=-1" -p
#
<%
   h=ENV['HASH'].split(',').map{ |s| s.split('=') }.to_h
   # inputs
   species1 = h['species1']
   source1  = h['source1']
   species2 = h['species2']
   source2  = h['source2']
   # options
   by_gene  = h['by_gene']
   paired   = h['paired']
%>

<%= File.read(File.dirname(__FILE__)+'/preamble.rq')  %>

<% if not by_gene %>
  <% if paired %>
    SELECT DISTINCT ?cluster ?hcluster WHERE 
  <% else %>
    SELECT DISTINCT ?cluster WHERE 
  <% end %>
<% else %>
  SELECT ?cluster ?hcluster ?hname WHERE 
<% end %>
{

  ?cluster
    :species "<%= species1 %>" ;
    :source "<%= source1 %>" ;
    :lnL ?lnl .
  ?hgene
    a :blast_match ;
    :homolog_species "<%= species1 %>" ;
    :homolog_source "<%= source1 %>" ;
    :homolog_cluster ?cluster ;  # match all genes in cluster
    :cluster ?hcluster ;
    rdf:label ?hname .
    FILTER (CONTAINS(?hname,"<%= species2+'_'+source2 %>") && (?cluster != ?hcluster)) . 
}
