prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix dc: <http://purl.org/dc/elements/1.1/>
prefix gwp: <http://biobeat.org/rdf/gwp#> 
prefix paml: <http://biobeat.org/rdf/paml#> 
prefix blast: <http://biobeat.org/rdf/blast#>
prefix gene: <http://biobeat.org/rdf/gwp/gene-names#> 
prefix signalp: <http://biobeat.org/rdf/signalp#> 
prefix phobius: <http://biobeat.org/rdf/phobius#> 
prefix : <http://biobeat.org/rdf/ns#> 

