# List all clusters that have signalP
#
# ./scripts/sparql.sh script.rq
# 

<%= File.read(File.dirname(__FILE__)+'/preamble.rq')  %>

SELECT ?cluster ?gene_name WHERE 
# SELECT distinct ?cluster WHERE 
{
  ?id      :signalP true .
  ?id      :gene_name ?gene_name .
  ?id      :species ?species .
  ?id      :source ?source .
  ?id2     :gene_name ?gene_name .
  ?id2     :species ?species .
  ?id2     :source ?source .
  ?id2     :cluster ?cluster .
}
