# List all clusters that have signalP
#
# ./scripts/sparql.sh script.rq
# 

<%= File.read(File.dirname(__FILE__)+'/preamble.rq')  %>

# SELECT ?cluster ?gene_name WHERE 
SELECT distinct ?cluster WHERE 
{
  ?gene    :signalP true .
  ?gene    :gene_name ?gene_name .
  ?geneid  :gene_name ?gene_name .
  ?geneid  :cluster ?cluster .
}
